{
 "title": "Redis-Graphql",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Ops/Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "Operations/second" }
   ],
   "targets": [
    {
     "expr": "rate(redisgraphql_ft_searches_count[1m])",
     "legendFormat": "Search"
    },
    {
     "expr": "rate(redisgraphql_agg_count_count[1m])",
     "legendFormat": "AggCount"
    },
    {
     "expr": "rate(redisgraphql_agg_numgroup_counts[1m])",
     "legendFormat": "AggNumGroup"
    },
    {
     "expr": "rate(redisgraphql_agg_raw_counts[1m])",
     "legendFormat": "AggRaw"
    }
   ]
  },
  {
   "title": "Docs Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Redisearch Docs/Second" }
   ],
   "targets": [
    {
     "expr": "rate(redisgraphql_docs_count[1m])",
     "legendFormat": "Docs"
    }
   ]
  },
  {
   "title": "Graphql Durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms", "label": "Graphql Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(redisgraphql_graphql_duration_milliseconds_bucket[5m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(redisgraphql_graphql_duration_milliseconds_bucket[5m])) by (le))",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Redisearch Durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms", "label": "Redisearch Fetch Times" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(redisgraphql_redis_duration_milliseconds_bucket[5m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(redisgraphql_redis_duration_milliseconds_bucket[5m])) by (le))",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Redis Pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    { "expr": "redisgraphql_pool_active", "legendFormat": "Active" },
    { "expr": "redisgraphql_pool_idle", "legendFormat": "Idle" },
    { "expr": "redisgraphql_pool_wait", "legendFormat": "Wait" }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    { "expr": "redisgraphql_query_errrors", "legendFormat": "Query" },
    { "expr": "redisgraphql_post_errrors", "legendFormat": "Post" }
   ]
  }
 ]
}